root = "."
tmp_dir = "tmp"

[build]
pre_cmd = ["npx tailwindcss -o ./static/tailwind.css", "templ generate"]
include_ext = ["go", "tpl", "tmpl", "html", "templ", "js", "json"]
exclude_regex = ["_test\\.go", "_templ.go"]
